---
- name: Post STIG Configuration
  hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ansible_become: yes
    ansible_become_user: root
    ansible_become_password: BigNavyGrayShip2021
    ansible_become_method: su

  tasks:
  - name: Remove NOPASSWD in sudoers.d
    shell: sed -i 's/NOPASSWD/PASSWD/g' /etc/sudoers.d/*
  - name: Remove comments in sudoers.d
    shell: sed -i '/\#/d' /etc/sudoers.d/*
  - name: File for ec2-user exists
    ansible.builtin.file:
      path: /etc/sudoers.d/ec2-user
      state: touch
      owner: root
      group: root
      mode: '0600' 
  - name: Remove NOPASSWD
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/ec2-user
      regexp: 'NOPASSWD'
      state: absent
  - name: Sudo file for ec2-user contains the proper data
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/ec2-user
      state: present
      line: 'ec2-user ALL=(ALL) PASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
  - name: Update fapolicy.d
    ansible.builtin.lineinfile:
      path: /etc/fapolicyd/fapolicyd.conf
      regexp:  'permissive'
      line: permissive = 1 
  - name:  Restart fapolicyd Daemon    
    command: systemctl restart fapolicyd
  - name: Update sshd
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp:  'PasswordAuthentication no'
      line: PasswordAuthentication yes
  - name:  Restart sshd Daemon    
    command: systemctl restart sshd
  - name: Set boot password - STIG Complaince 
    ansible.builtin.lineinfile:
      create: yes
      path: /boot/grub2/user.cfg
      regexp: 'GRUB2_PASSWORD'
      line: GRUB2_PASSWORD=grub.pbkdf2.sha512.10000.24F1AD56A287FD7FC0487BD697E830D91C2AFBEFB89D6C0B745EDA45B19E4B19196C3C6C53B7A9A76A5354C53DA0CB97B52B3E00FD03ACE1C7F64947457A03C0.7CEA5A535E9A0286EE82DF6B25090A37E64E21E6CA5766007F89B0A88BACC4B0ECB332B34B1D188737ECB9D98C21E519E6EEB68BB1EC6FE6E1E77333AC8C7E42
  - name: Faillock settings silent - STIG Compliance
    ansible.builtin.lineinfile:
      path: /etc/security/faillock.conf            
      regexp: 'silent'
      line: silent
  - name: Faillock settings audit - STIG Compliance
    ansible.builtin.lineinfile:
      path: /etc/security/faillock.conf            
      regexp: 'audit'
      line: audit
  - name: Blacklist file
    ansible.builtin.copy:
      src: blacklist.conf
      dest: /etc/modprobe.d/blacklist.conf
      owner: root
      group: root
      mode: 0644      
  - name:  Custom TMUX - STIG Compliance
    ansible.builtin.copy:
      src: custom.sh
      dest: /etc/profile.d/custom.sh
      owner: root
      group: root
      mode: 0644     
  - name: Remove TMUX from etc shells
    ansible.builtin.lineinfile:
      path: /etc/shells
      state: absent
      regexp: 'tmux'
  - name: Chrony should not act as a server
    ansible.builtin.lineinfile:
      path: /etc/chrony.conf
      state: present 
      line: port 0 
  - name: Chrony should not network management
    ansible.builtin.lineinfile:
      path: /etc/chrony.conf
      state: present 
      line: cmdport 0 
  - name: Umount should be 0755 
    ansible.builtin.file:
      path: /usr/bin/umount
      mode: '0755'    

      ###
  - name: Update sshd
    ansible.builtin.lineinfile:
      path: /usr/lib/sysctl.d/50-coredump.conf
      regexp:  'kernel.core_pattern='
      line: '# kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e'
      ### 

  - name: kernel.core_pattern = |/bin/false
    sysctl: 
      name: kernel.core_pattern
      state: present
      sysctl_set: yes
      value: '|/bin/false'



  - name: Reboot after update
    reboot: 
